### ISSUE TITLE
Estimate when pool-fee-wallet will be supported

### ISSUE THREAD

**Issue by DeMemeTree** [minexmr2/minexmr2#3]
How does the pool operator maintain a balance of their own if their own balance is mixed in with the pools balance. 

Having pool-fee-wallet to collect the pool fees seems like a much needed thing.

Any ETA on this?

**Comment by minexmr2** [comment]
if one doesn't use that option, unlocked pool wallet balance in a time moment just after miners' reward payout tx belongs to pool's owner.

pool-fee-wallet entry in pool.conf is not supported yet, if pool compiled with p2pool support. I'll implement that as soon as possible.
