### ISSUE TITLE
Pool stopped paying out (not minexmr2.com, another instance)

### ISSUE THREAD

**Issue by DeMemeTree** [minexmr2/minexmr2#4]
The pool stopped paying out and somehow my balance has become absurd with out much XMR I am owed..

9.2 Million XMR that it owes my mining address. The pool XMR balalance just keeps increasing and it hasnt made a payout in 3 days. After first it was awesome and everything was running smoothly but something weird has happened. I was able to mine about 0.3 XMR and get paid out that in ~0.01 incrememnts. However, that has now stopped and the pools balance is increasing well above 0.2 without making another payout to myself.

Is there any debug info I can get you to help diagnose the issue? I believe maybe I was mining when p2pool wasnt totally synced maybe like on a cpu restart or something?

If thats the case shouldnt minexmr2 detect when p2pool isnt fully synced? Im worried about deploying this to production now unless I can resolve this issue and prevent it from happening again. I have everything running as systemd services

**Comment by minexmr2** [comment]
First of all, write your XMR address and estimated XMR value you've excepted to receive but still missing. I'll make you a manual payout.

Email to write: minexmr2@tutanota.com.

Now I am investigating the issue...

**Comment by minexmr2** [comment]
I've just checked the logs and pending balances. No error found in logs, no XMR address with balance above 0.02 or even 0.01XMR... Also I have a test XMR address since I mine to my pool myself too, and test address have received all the payments on its side (independent monerod, monero-cli-wallet utilities on an independent PC).

Waiting your email to minexmr2@tutanota.com...

**Comment by minexmr2** [comment]
P.S. If connection between minexmr2 and p2pool catches any error (via libevent), then connection between a miner and minexmr2 gets closed automatically. if p2pool is in async/error state, it refuses incoming connections. In this case, xmrig app tries to reconnect to the pool in specified time intervals (you can tune xmrig reconnection behavior in its config.json file). Thus, while xmrig is trying to reconnect, it is not mining (and consuming CPU/RAM resources).

I will implement email notifications from the pool side. But in your case (have everything running as systemd services), it is better to tune xmrig's config.json file for proper behavior on lost connection to the minexmr2 pool.

**Comment by jeffrey-cripe** [comment]
This is a locally run instance. Sorry I should of specified I am running the software not mining to your minexmr2 pool that you host.

**Comment by DeMemeTree** [comment]
I am not mining directly to the instance of minexmr2 that you host.

I am running this locally on an ubuntu instance.

 Im just confused on how the mining pool was telling me that I was owed well over 9 million monero. I am the only one mining to the pool I am maintaining. I figured somehow the pool was able to mine on p2pool when it wasnt totally synced with the network. This is a guess but Im assuming it would make the difficulity very low if it wasnt totally synced. 
 
 Somehow the locally run pool that I am maintaining from following all the guides etc stopped paying out and my balance I was "owed" was crazy amount. Ive sinced nuked the instance that I was running and have started fresh so will keep an eye out for any weird behavior but I still think it was due to a restart and p2pool wasnt fully synced and so the difficulity was super ez thus making my balance owed of like 9 million xmr but thats just a guess

**Comment by minexmr2** [comment]
Just to check I've understood you correctly: you are running a minexmr2 instance compiled by yourself, right?

**Comment by DeMemeTree** [comment]
Yes that is indeed correct

**Comment by DeMemeTree** [comment]
Do you have discord? Is there anyway I can get in touch with you directly to ask you questions in a DM? I would pay in Monero for a consulting fee

**Comment by minexmr2** [comment]
I have no Discord currently. Public material you may place here, private by email. But I have understand your issue, and know where to search for possible bugs. Thank you pretty much. I let you know if I need your help, but I think today I indeed know where to search...

**Comment by DeMemeTree** [comment]
Any luck on this? Other wise I can take a crack at the code. The problem is when p2pool starts up and has a low difficulity Im able to mine blocks to the pool where I really shouldnt be. I was able to get it to happen again so will likely try to fix it if you havent already

**Comment by minexmr2** [comment]
In any case, you fix variant is welcome, feel free to make a pull request, and/or describe your approach here.
