### ISSUE TITLE
What needs to be done in order to prepare for p2pool hardfork?

### ISSUE THREAD

**Issue by DeMemeTree** [minexmr2/minexmr2#6]
Anything?

**Comment by minexmr2** [comment]
As [sech1 wrote](https://www.reddit.com/r/MoneroMining/comments/1095730/comment/j40acyg/?utm_source=share&utm_medium=web2x&context=3), nothing special, I'll just upgrade to p2pool 3.0 as usual.

**Comment by DeMemeTree** [comment]
I believe rx_slow_hash interface on monero changed and your xmr.cpp no longer compiles. I tried my hand at it but got weird results when I tried to modify stuff when running the pool.

**Comment by minexmr2** [comment]
What do you mean? rx_slow_hash() is a part of monero source code, not p2pool one. What configuration have you tried to compile? Could you place a GitHub tag/commit links and/or p2pool GitHub tag/commit links to determine exactly your build configuration?

**Comment by DeMemeTree** [comment]
latest release v18 branch and then the latest branch of this.

**Comment by minexmr2** [comment]
I think to eliminate monero's rx_slow_hash()-like dependencies because they are needed to share verification in non-p2pool mode (i.e. classic pool mode). monero-pool will support p2pool only and obsolete code will be pruned out.
